name: Guild Lambda Deploy Pipeline

on:
  workflow_dispatch:  # Manual trigger
  push:              # On push to main
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: test  # GitHub env for secrets
    permissions:
      id-token: write
      contents: read
      checks: write    # For test reporting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r iac/requirements.txt

      - name: Install AWS CLI and CDK
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          npm install -g aws-cdk@2.140.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # OIDC role for test account
          aws-region: us-west-2

      - name: Run unit tests
        run: |
          cd src
          python -m pytest test_validation.py -v --cov=hello_app --cov-report=xml
        env:
          LOG_LEVEL: INFO

      - name: Security scan (basic dependency check)
        run: |
          pip check  # Check for vulnerable deps
          # Optional: Add pip-audit if available

      - name: Lint code
        run: |
          cd src
          black --check .
          flake8 .

      - name: Bootstrap CDK (if needed)
        run: |
          cd iac
          cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/us-west-2

      - name: Deploy to Test Environment
        if: github.ref == 'refs/heads/main'  # Only deploy on main push
        run: |
          cd iac
          cdk deploy --require-approval never --context env=test
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID_TEST }}
          CDK_DEPLOY_REGION: us-west-2

      - name: Post-deployment validation
        if: github.ref == 'refs/heads/main'
        run: |
          # Fetch API URL from CDK outputs (parse from cdk.out)
          API_URL=$(cd iac && cdk deploy --require-approval never --outputs-file outputs.json && jq -r '.GuildLambdaStack.ApiEndpoint' outputs.json)
          curl -f $API_URL  # Basic health check
          echo "Deployment successful: $API_URL"
          